version: '3'

services:
  dockerwebexample:
    image: dockerwebexample
    links:
      - bookswebapi
    build:
      context: ./DockerWebExample
      dockerfile: Dockerfile

  bookswebapi:
    image: bookswebapi
    depends_on:
      - db
    build:
      context: ./BooksWebAPI
      dockerfile: Dockerfile

  db:
    image: "microsoft/mssql-server-windows-express"
    environment:
      SA_PASSWORD: "popcorn06!"
      ACCEPT_EULA: "Y"